services:
  gpu-test:
    container_name: gpu-test
    build:
      dockerfile: ./Dockerfile
    healthcheck:
      test: nvidia-smi
      interval: 3s
      timeout: 1s
      retries: 3
    command: sleep infinity
